### ISSUE TITLE
Python tidy up

### ISSUE THREAD

**Issue by fizzyade** [AaronDMarasco/pingnoo#3]
Hi Aaron,

I'm cleaning up the python according to the warnings that I am seeing in CLion/pyCharm, and in the common module you append each function to __all__.

This is causing a warning to appear because there's not 2 line breaks between __all__ and the actual function definition.  Now, I understand why you've put it up against the def, but I'm not sure whether or not to move stuff to rid the warning, so instead of the __all__ being next to the function, then can appear as a block:

```
__all__.append('ExecuteException')
__all__.append('timedelta')
__all__.append('write_msg')
__all__.append('bad_msg')
__all__.append('parent')
__all__.append('rm_file')
__all__.append('rm_path')
__all__.append('execute')
__all__.append('which')
__all__.append('run')
```

This rids the warning, but whether it's a good "change" is a different matter.  It makes things harder to match up.

Now, is this a reasonable change according to general python coding guidelines?  Or should I just disable the warning in the file for my IDE?

**Comment by AaronDMarasco** [comment]
I did that as a personal call because that's what I do at work. Your options are:

- Do it "right" and just have at the top of the file `__all__ = ['ExecuteException', 'timedelta' ... ]`
- Keep it the way I have it.

The justification I use for doing it "my way" is that we have like 4 different projects in my office. If there's a cool utility function in one we want to steal, you just grab that function definition. And lo and behold, the line right above it is adding it to `__all__` so you have a nice and minimal/localized `git` changeset and less chance of a conflict later. If it was done "right" then you're more likely to get a merge conflict on the single `__all__` line, so we avoid that.

Since your project is pretty much a one-man show, doing it the "proper" way is likely better; I don't foresee you adding functions to those libraries in different branches a whole lot. I just did it this way out of habit.

**Comment by fizzyade** [comment]
Thanks for the comprehensive reply!  I'll mull it over, it's purely just a "tidy" exercise for me to clear the warnings in CLion/PyCharm, I can see the advantages in the way you've done it and the justification for doing it that way.

As you say, it's unlikely that these functions will be used anywhere else or that they'll change substantially, I didn't want to make a change for the sake of making a change and making things unclearer in the code you've written, purely just to remove a warning or two.

I'm currently just going through the code cleaning things up as I go, I've just added a couple of minor changes to allow the building of a raspberry pi package which Is why I ended up looking at the python.  I've spent the last couple of weeks doing housekeeping on the project, making changes where I know that things aren't quite right so that going forward things are right.

The deployment script and the work you have put in has made my life so much easier, creating deployable images is an absolute breeze, I just hit run on TeamCity and out pop all the images ready for uploading to GitHub and packagecloud and the AUR.  

Although up to now I've only been building 64-bit packages, I added support for Windows to build "portable" zip files for both x86 and x86_64, x86 means that it's properly portable on Windows and I'm going to upload it to portableapps.com which meant that I had to have a 32-bit version.  I updated the Windows installer to make it a 32/64-bit combined installer, so it installs the correct version depending on the OS.  

I would build Linux 32-bit versions as well, but to do that I need another intel NUC with 64GB RAM so that I can create build containers.  My current NUC (which has 64GB) doesn't have much RAM left with all the containers I spun up on proxmox for the build containers, it also runs an OPNsense VM which is my network firewall.  It's a shame TeamCity can't just spin up proxmox containers on-demand to build because that would solve the problem.

Behind the scenes work doesn't give you flashy releases, but it does set the foundations and building blocks for the future.
